baseURL = ''
languageCode = 'en-us'
title = 'DirectPV Docs by MinIO'
theme = 'kes-docs-theme'
relativeURLs = "True"
enableGitInfo = true

[params]
    footerText = 'This work is licensed under a Creative Commons Attribution 4.0 International License. 2020-Present, MinIO, Inc.'
    homeLink = '/'

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
	[markup.highlight]
		noclasses = false
